# Анализ вакансии для аналитиков данных на Linkedin

**Цель:** Визуализировать информацию о рынке вакансий для аналитиков в Европе

**Источник данных:** информация с сайта linkedin.com. Данные извлечены из html-кодов страниц 23 мая 2023 г.

## Представление обработанных данных в Tableau

ссылка на Tableau: https://public.tableau.com/app/profile/liudmila2867/viz/DADS/Dashboard2?publish=yes

## Предобработка данных

Начнем с того, что ознакомимся с данными перед обработкой (загрузим данные, выведем датасет для ознакомления, определим типы данных, пропущенные значения и дубликаты)

In [1]:
# импортируем необходимые библиотеки

import pandas as pd

In [2]:
# загрузим датасет
data = pd.read_csv('D:\linkedin.csv')

In [3]:
# изучим датасет

df = data.copy()
df.head(15)

,title,location,country,employment_type,company_name,employee_qty,company_field,skills,job_description,applicants
0,Data Analyst,Basel,Switzerland,On-site,PharmiWeb.Jobs: Global Life Science Jobs,11-50 employees,Staffing and Recruiting,None,What You Will Achi...,47.0
1,Data Analyst - Logistics,Coventry,United Kingdom,On-site,Resolute Recruitment,not specified,not specified,None,,NaN
2,Data Analyst - Logistics,Coventry,United Kingdom,On-site,Resolute Recruitment,not specified,not specified,None,Data Analyst - Lo...,NaN
3,Data Analyst (Space & Planning),South Molton,United Kingdom,On-site,Mole Valley Farmers,not specified,not specified,None,Salary: To b...,NaN
4,Data Analyst,Lugano,Switzerland,On-site,FORFIRM,not specified,not specified,None,FORFIRM is p...,NaN
5,Data Analyst - Logistics,Southampton,United Kingdom,On-site,"Butler, Bridge & May",not specified,not specified,None,Location: Southam...,NaN
6,Data Analyst,Leeds,United Kingdom,On-site,Maria Mallaband Care Group Ltd,not specified,not specified,None,We’re Maria Malla...,NaN
7,Data Analyst,Nuneaton,United Kingdom,Hybrid,Kelly Group,not specified,not specified,None,Kelly Group are s...,NaN
8,Data Analyst,Paris,France,On-site,eXalt,"501-1,000 employees",IT Services and IT Consulting,"<span class=""visually-hidden""><!-- -->Skills: ...",Qui sont-ils ? ...,140.0
9,Data Analyst - Hybrid Working,Cambridge,United Kingdom,On-site,Blue Arrow,not specified,not specified,None,Data Analyst ...,NaN
10,Data Analyst,West Midlands,United Kingdom,On-site,Mexa Solutions,not specified,not specified,None,Hybrid - West Mi...,NaN
11,Commercial Data Analyst,Schiphol,Netherlands,On-site,Royal Schiphol Group,"1,001-5,000 employees",Airlines and Aviation,"<span class=""visually-hidden""><!-- -->Skills: ...",De functie Welk...,13.0
12,Asset Data Analyst,Chester,United Kingdom,On-site,networx | Recruitment Software & Services by IRIS,not specified,not specified,None,Do you have the d...,NaN
13,Data Analyst - Hybrid,Cambridge,United Kingdom,On-site,Blue Arrow,not specified,not specified,None,Data Analyst ...,NaN
14,Data Analyst,Craven Arms,United Kingdom,not specified,networx | Recruitment Software & Services by IRIS,not specified,not specified,None,Are you passionat...,NaN

In [4]:
# изучим пропуски и типы данных 

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 998 entries, 0 to 997
Data columns (total 10 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   title            998 non-null    object
 1   location         998 non-null    object
 2   country          998 non-null    object
 3   employment_type  998 non-null    object
 4   company_name     996 non-null    object
 5   employee_qty     998 non-null    object
 6   company_field    998 non-null    object
 7   skills           998 non-null    object
 8   job_description  998 non-null    object
 9   applicants       838 non-null    float64
dtypes: float64(1), object(9)
memory usage: 78.1+ KB

In [5]:
# найдем пропущенные значения в датасете

df.isnull().sum().sort_values(ascending=False)

applicants         160
company_name         2
title                0
location             0
country              0
employment_type      0
employee_qty         0
company_field        0
skills               0
job_description      0
dtype: int64

Имеет смысл также выявить неявные пропуски в столбцах ('None','0','not specified')

In [6]:
# изменим тип данных в столбце applicants на стороковый для возможности выполнения следующего цикла

df['applicants'] = df['applicants'].astype('str')

In [7]:
# проверяем каждый столбец на наличие неявных пропусов

for i in df.columns:
    #del df['job_description']
    print('Столбец:',i)
    print('Количество уникальных неявных пропущенных значений в столбце:',df[df[i].str.contains('None')|df[i].str.contains(' 0 ')|\
    df[i].str.contains('not specified')][i].nunique())
    print(df[df[i].str.contains('None')|df[i].str.contains(' 0 ')|\
    df[i].str.contains('not specified')][i].unique())
    continue

Столбец: title
Количество уникальных неявных пропущенных значений в столбце: 0
[]
Столбец: location
Количество уникальных неявных пропущенных значений в столбце: 0
[]
Столбец: country
Количество уникальных неявных пропущенных значений в столбце: 0
[]
Столбец: employment_type
Количество уникальных неявных пропущенных значений в столбце: 1
['not specified']
Столбец: company_name
Количество уникальных неявных пропущенных значений в столбце: 0
[]
Столбец: employee_qty
Количество уникальных неявных пропущенных значений в столбце: 1
['not specified']
Столбец: company_field
Количество уникальных неявных пропущенных значений в столбце: 1
['not specified']
Столбец: skills
Количество уникальных неявных пропущенных значений в столбце: 1
['None']
Столбец: job_description
Количество уникальных неявных пропущенных значений в столбце: 11
["                            bloomon is turning the flower industry on its head – for the better. How? By disrupting the traditional supply chain, where most florists operate offline and have done for decades. bloomon creates seasonal collections using unusual stems to deliver unique flower arrangements on repeat or as a unique gift. We always use field-fresh high-quality flowers straight from the grower and deliver them to our customers through a high-tech and highly creative platform.   We launched in Amsterdam in 2014 and went from start-up to scale-up at hypersonic speed. In 2021 we joined forces with Bloom &amp; Wild, the UK's fastest-growing e-commerce company (according to the Financial Times). Driven by our vision of creating the destination for making life a little more thoughtful and beautiful, we're now part of Europe's leading online flower company.   Our group is backed by top-tier investors including General Catalyst (backers of Airbnb and Deliveroo), who led our £75 million Series D funding round in January 2021, alongside Index Ventures (investors in Wise and Glossier). We are home to a family of 3 strong brands, Bloom &amp; Wild, bloomon, and Bergamotte. Together, we are active in 8 countries.   We really care about creating a diverse and inclusive team and we welcome people from all backgrounds, with different perspectives, ideas and experiences to work with us. In our team, everyone has the freedom to give their opinion, grow in their career and be part of a genuinely caring and inclusive team.    The team    We’re on a mission to make data at the heart of what we do as at Bloom &amp; Wild. You’ll work closely with the Operations team to drive data driven decision making within all areas of Operations. You’ll be joining the Analytics &amp; BI team and there will also be the opportunity to work with and learn from the rest of the team.    The role    We’re looking for an Operations Analyst to join our team. Reporting to the area lead of the BI Operations team as they optimise getting our products from farm to recipient in the most efficient way possible. This newly created role has lots of potential for future growth.    Please note that only applicants with intermediate- advanced hands-on SQL experience will be considered. This will be tested during the application process.       You'll have ownership of Operations Squad’s analytical roadmap (with support as needed) and be responsible for sizing and prioritising work to deliver the most impactful and timely insights.   You will work with several key parts of the Operations team these include:   Fulfillment &amp; Delivery - working closely with the team to ensure that we effectively track fulfillment and carrier partner performance that optimises customer satisfaction and profitability.   Trading team - working closely with this team to ensure the optimal amount of stock to sell and avoid any wastage.   Sustainability - we are actively working to be a net 0 emissions company. You’ll be working with our sustainability team in order to understand the data needs, and challenges as well as focus on the key areas of impact.   Own fulfilment team - we have different warehouses in different countries. You will help provide this team with reporting to help optimise customer satisfaction.   Supply Chain and Quality - You will help this team to measure the quality of products including non floral gifts. You will create reporting to ensure that we achieve a high customer NPS and provide recommendations if you identify any areas for improvement.   Customer delight- You will support the customer delight team to understand the performance of our help centre, providing recommendations on areas we could look to improve.   This role will be a combination of building reporting and investigative analysis. You will be able to navigate the opportunities/challenges of both.   You are focused on the most valuable and high impact work and are not afraid to push back on requests if they do not have a clear impact/use.   This role is fast paced, so it will be important that you'll be able to identify quick wins and make trade-offs while maintaining analytical best practice.   You'll provide robust and easy to understand recommendations from your analysis that can be explained to technical and non-technical colleagues.   You have strong communication skills and you're a team player. You'll use these skills to develop strong relationships throughout the business.   You will be action-oriented and ensure that recommendations feed the long-term roadmap.      You       Have at least 3 years of hands-on day to day SQL experience- intermediate/advanced level required. This will be used every day and is a mandatory requirement of the role.   Proven track record (and examples) of creating actionable insight and recommendations which have driven business impact   Track record of working independently to shape analytical problems and define testing methodologies   Experience working with Tableau (or other reporting tools)   Previous experience of automating reporting and simple tasks   A strong attention to detail coupled with an ability to identify big-picture opportunities to add value     Why bloomon?   Bloom &amp; Wild Group teams are distributed across office locations in Amsterdam and London, and multiple warehouse locations. We’re working hard to create a culture of inclusion for our teams, whether they’re working from the office or home. And so whether you need to be at home for focus time or for school pickup, or you want to spend time together with your co-workers, we’ll do our best to make your experience a good one!     Bloomon Perks &amp; Benefits        24 vacation days, with an option to buy an extra 5 vacation days.   1 celebration day per year (extra day off to celebrate a holiday that is important to you)   Happiness days (4 extra days off per year for your personal “me-time”)   We’ll support your commute to our office and site locations. Depending on your journey to work, this may include a - VanMoof bike, an NS business card or expense reimbursement   Access to the GoodHabitz platform for personal development   Access to OpenUp online therapy for your mental health   We love having lunch together! We offer daily fresh and healthy lunch options at our locations in Amsterdam and Amstelveen,   A BBQ-worthy rooftop terrace (Amsterdam HQ)   Friday drinks and socials   Weekly online yoga classes   We’ll provide you with a laptop and other necessary equipment   Phone allowance   Discounts on our beautiful products!     We all love what we do – so if you like challenges, developing new skills, growing creatively and taking initiative, you’ll feel right at home at bloomon!                        "
 "                            Bloom &amp; Wild is re-inventing the $60B global flower industry. Over a billion flower exchanges take place every year and industry satisfaction levels are low. Driven by our vision of creating the destination for making life a little more thoughtful and beautiful, we do things differently. From inventing letterbox flowers to founding The Thoughtful Marketing Movement. And we’ve seen impressive traction to date - we are Europe’s largest direct to consumer flower company.   In January 2021 we announced our £75 million Series D funding round, led by General Catalyst (backers of Airbnb and Deliveroo), alongside other top tier investors including Index Ventures (investors in Wise and Glossier). We are home to a family of 3 strong brands, Bloom &amp; Wild, bloomon and Bergamotte, having acquired bloomon in April 2021 and Bergamotte in July 2021. Together, we are active in 8 countries.   We really care about creating a diverse and inclusive team and we welcome people from all backgrounds, with different perspectives, ideas and experiences to work with us. In our team, everyone has the freedom to give their opinion, grow in their career and be part of a genuinely caring and inclusive team.    The team    We’re on a mission to make data at the heart of what we do as at Bloom &amp; Wild. You’ll work closely with the Operations team to drive data-driven decision-making within all areas of Operations. You’ll be joining the Analytics &amp; BI team and there will also be the opportunity to work with and learn from the rest of the team.    The role    We’re looking for an Operations Analyst to join our team. Reporting to the area lead of the BI Operations team as they optimise getting our products from farm to recipient in the most efficient way possible. This newly created role has lots of potential for future growth.    Please note that only applicants with intermediate- advanced hands-on SQL experience will be considered. This will be tested during the application process.       You'll have ownership of Operations Squad’s analytical roadmap (with support as needed) and be responsible for sizing and prioritising work to deliver the most impactful and timely insights.   You will work with several key parts of the Operations team these include:   Fulfillment &amp; Delivery - working closely with the team to ensure that we effectively track fulfillment and carrier partner performance that optimises customer satisfaction and profitability.   Trading team - working closely with this team to ensure the optimal amount of stock to sell and avoid any wastage.   Sustainability - we are actively working to be a net 0 emissions company. You’ll be working with our sustainability team in order to understand the data needs, and challenges as well as focus on the key areas of impact.   Own fulfilment team - we have different warehouses in different countries. You will help provide this team with reporting to help optimise customer satisfaction.   Supply Chain and Quality - You will help this team to measure the quality of products including non floral gifts. You will create reporting to ensure that we achieve a high customer NPS and provide recommendations if you identify any areas for improvement.   Customer delight- You will support the customer delight team to understand the performance of our help centre, providing recommendations on areas we could look to improve.   This role will be a combination of building reporting and investigative analysis. You will be able to navigate the opportunities/challenges of both.   You are focused on the most valuable and high impact work and are not afraid to push back on requests if they do not have a clear impact/use.   This role is fast paced, so it will be important that you'll be able to identify quick wins and make trade-offs while maintaining analytical best practice.   You'll provide robust and easy to understand recommendations from your analysis that can be explained to technical and non-technical colleagues.   You have strong communication skills and you're a team player. You'll use these skills to develop strong relationships throughout the business.   You will be action-oriented and ensure that recommendations feed the long-term roadmap.      You       Have at least 3 years of hands-on day to day SQL experience- intermediate/advanced level required. This will be used every day and is a mandatory requirement of the role.   Proven track record (and examples) of creating actionable insight and recommendations which have driven business impact   Track record of working independently to shape analytical problems and define testing methodologies   Experience working with Tableau (or other reporting tools)   Previous experience of automating reporting and simple tasks   A strong attention to detail coupled with an ability to identify big-picture opportunities to add value      Working Environment    We are a distributed team with two office locations in Amsterdam and London and multiple warehouse locations. To maximise learning and cross-collaboration, the UK commercial and trading teams, and the majority of the UK teams we collaborate with, work from our London office 2-3 days per week. A similar amount of in person time is preferred, but not a requirement for this role, but it is worth noting that during our peak weeks (Christmas, Valentine’s Day, Mother’s Day) the whole commercial team will be office based.   We’re working hard to create a culture of inclusion for our teams, whether they’re working from the office or home. And so whether you need to be at home for focus time or for a school pickup, or you want to spend time with your co-workers, we’ll do our best to make your experience a good one!     Our Perks And Benefits        25 days holiday, with an additional day off for your birthday, plus bank holidays, totalling 34 days, per year. There is also the option to buy an extra 5 days holiday each year   Flexible working schedule (core hours from 10-4pm)   We offer flexible bank holidays so you can trade a bank holiday day off and in its place take off another day that fits better with your beliefs, values and celebration calendar   Choose your laptop and any extra equipment you need to do your best work   Health cash plan through Simplyhealth   Personal development budget   Enhanced Family Friendly policy   Financial wellbeing support through Bippit   Workplace nursery - a salary sacrifice based childcare scheme   Cycle to work scheme   Pension contribution   Discounts on our blooms!   Lunch &amp; learns   Bloom &amp; Go Wild trips       We Have An Informal, Inclusive And Scale-up Culture, And Those Who Choose To Come Into The Office, Also Benefit From     Our lovely, light and spacious office is conveniently located close to Vauxhall and Oval stations in London.      A kitchen stocked with snacks + a beer, wine and soft drinks fridge   Early finishes on Thursdays &amp; Fridays to spend more time with each other   We love to get together to celebrate! Events include Summer &amp; Christmas parties, post peak celebrations and team lunches     In addition, we’re supporting each other and maintaining our culture remotely through:      Weekly online yoga class   Celebration of birthdays, anniversaries, and special occasions   Weekly Stand Up and Monthly Meetings to celebrate our successes and value nominations   Wellbeing support through our online platform, Open Up, which offers online therapy sessions                          "
 '                             What We Offer\u202f      Enjoy a high level of responsibility and immediate client interactions under the guidance of senior team members.  Help our clients to target, measure, and improve mission-critical business metrics and generate a demonstrable return on investment.  Working with other Senior Data Scientists to take data throughout its lifecycle - acquisition, exploration, data cleaning, integration, analysis, interpretation, and visualization.  Become part of a fast-growing international and diverse team.      Who We Are    We are Metyis. We are a dynamic and forward-thinking consultancy firm that operates across a wide range of industries, creating solutions that are tailored to specific needs. We bring long-lasting impact and growth to our partners and clients.   With our multidisciplinary teams we create bold strategies and innovative solutions that are tailored to our client’s needs and help them capitalizing opportunities. Together we strive to bring long-lasting impact and celebrate collective victories.   At Metyis we share an entrepreneurial mindset, a compelling passion to create, and, more importantly, a firm belief in our partnership-driven business model. This is embedded in our culture and safeguarded as we evolve. Our team counts over 450 ambitious professionals with various backgrounds, spread over several continents. Our work environment unifies creative problem-solving and strategic thinking. We provide resources to visionaries who understand the direction that the world is moving. Tomorrow’s world is data-driven. It is digital. It is international.   Become part of the journey, become part of Metyis. Partners for impact.    What You Will Do\u202f      Performing data analysis in the field of Marketing Analytics, CLM/CRM analytics, and/or Risk analytics  Analyses conducted in typical analytical tools ranging from SAS, SPSS, Eviews, R, Python, SQL, Teradata, Hadoop, Access, Excel, etc.  Communicating analyses via compelling presentations  Solving problems, disaggregate issues, develop hypotheses, and develop actionable recommendations from data and analysis  Preparing and facilitating workshops  Managing stakeholders and communicating with executives      What you’ll bring\u202f\u202f      0 - 2 years of professional work experience in the analytics domain  An advanced degree in a quantitative field (e.g. mathematics, computer programming, etc.)  An ability to think analytically, decompose problem sets, develop hypotheses and recommendations from data analysis  Strong technical skills regarding data analysis, statistics, and programming. Strong working knowledge of, Python, Hadoop, SQL, and/or R.  Working knowledge of Python data tools (e.g. Jupyter, Pandas, Scikit-Learn, Matplotlib)  Ability to talk the language of statistics, finance, and economics a plus  Profound knowledge of the English language  Good to have experience in the Retail and/or Banking industry                          '

In [8]:
# возвращаем тип данных для столбца applicants
df['applicants'] = df['applicants'].astype('float')

In [9]:
# найдем задублированные строки

df.duplicated().sum()

112

**Вывод**:

- почти во всех столбцах (8 из 9) тип данных - строковый, в столбце applicants тип данных - вещественный. Тип данных во всех столбцах - корректный.
- наименования столбцов также представлены корректно (нижний регистр, нижнее подчеркивание в случае нескольких слов)
- в столбцах applicants (количество поданных заявок) и company_name имеются пропущенные значения (160 и 2 соответственно). Пропущенных значений в столбце сompany_name - всего два и название компании невозможно чем-то заменить. Имеет смысл рассмотреть столбец applicants
- в датасете имеются 112 строк-дубликатов
- в столбцах employment_type (тип занятости), employee_qty (количество сотрудников), company_field (область компании) пропуски заменены на not specified, т.е. в Linkedin компании решили не указывать эти данные
- в столбце skills есть неявные пропуски (None), однако, не целесообразно заполнять ячейки с пропущенными значениями, т.к. имеет этот столбец не будет анализироваться, а во-вторых, в этом столбце могут быть совершенно разная информация, в-третьих, если мы заполним данными из столбца job_description, то столбец skills просто продублирует job_description, а нам нужно уникальные данные из столбца skills
- в столбце job_description было найдены неявные пропуски, но они фигурируют в самих описаниях вакансии, поэтому можно сказать, что пропусков в столбце job_description - нет

**Причин пропуска значений в столбце applicants может быть 2:**
1) NaN = 0

2) Данные по этому параметру не спарсились

Поскольку данные по этому столбцу не повлияют на точность результатов (количество поданных заявок на вакансию нам не интересны), то можем сделать допущение, что NaN - это ноль.

In [10]:
# проверим, является ли пропущенные значения в столбце applicants (количество поданных заявок) нулем 
# (т.е. на данную вакансию никто не откликнулся)

df[df['applicants']==0]

Empty DataFrame
Columns: [title, location, country, employment_type, company_name, employee_qty, company_field, skills, job_description, applicants]
Index: []

In [11]:
# заполним пропущенные значения в столбце applicants нулем

df['applicants'] = df['applicants'].fillna(0)

**Вывод**:

- Пропущенные значения в столбце applicants - это ноль, поэтому пропущенные значения заменили нулем.

**Найдем неявные дубликаты в столбцах и заменим их**

In [12]:
# выявим количество уникальных наименований в столбцах
for i in df.columns:
    print('Столбец',i,'\n','Количество уникальных значений:',df[i].nunique(),'\n')

Столбец title
 Количество уникальных значений: 560

Столбец location
 Количество уникальных значений: 428

Столбец country
 Количество уникальных значений: 72

Столбец employment_type
 Количество уникальных значений: 4

Столбец company_name
 Количество уникальных значений: 669

Столбец employee_qty
 Количество уникальных значений: 19

Столбец company_field
 Количество уникальных значений: 122

Столбец skills
 Количество уникальных значений: 617

Столбец job_description
 Количество уникальных значений: 812

Столбец applicants
 Количество уникальных значений: 178

Поскольку неявные дубликаты смотрятся вручную, то проанализируем и заменим в случае необходимости неявные дубликаты в столбцах country, employment_type, employee_qty и company_field

In [13]:
# создадим функцию для поиска неявных дубликатов
def duplicated_column(i):
    print(sorted(df[i].unique()))

In [14]:
# создадим функцию для замены неявных дубликатов
def replace_name(data, i,name_old,name_new):
    data[i] = data[i].str.replace(name_old,name_new,regex=True).copy()

Столбец 'country'

In [15]:
# выведем уникальные значения для поиска неявных дубликатов
duplicated_column('country')

[' Austria', ' Belgium', ' Bulgaria', ' Croatia', ' Czechia', ' Denmark', ' Estonia', ' Finland', ' France', ' Germany', ' Greece', ' Hungary', ' Ireland', ' Italy', ' Latvia', ' Lithuania', ' Luxembourg', ' Malta', ' Monaco', ' Netherlands', ' Norway', ' Poland', ' Portugal', ' Romania', ' Slovakia', ' Spain', ' Sweden', ' Switzerland', ' United Kingdom', 'Amsterdam Area', 'Athens Metropolitan Area', 'Berlin Metropolitan Area', 'Brussels Metropolitan Area', 'Bulgaria', 'Cologne Bonn Region', 'Copenhagen Metropolitan Area', 'Denmark', 'Eindhoven Area', 'Finland', 'France', 'Germany', 'Greater Banska Bystrica Area', 'Greater Barcelona Metropolitan Area', 'Greater Dijon Area', 'Greater Lyon Area', 'Greater Madrid Metropolitan Area', 'Greater Milan Metropolitan Area', 'Greater Munich Metropolitan Area', 'Greater Munster Area', 'Greater Nuremberg Metropolitan Area', 'Greater Oslo Region', 'Greater Palma de Mallorca Metropolitan Area', 'Greater Paris Metropolitan Region', 'Greater Pau Area', 'Greater Verona Metropolitan Area', 'Hungary', 'Iasi Metropolitan Area', 'Ireland', 'Italy', 'Krakow Metropolitan Area', 'Lisbon Metropolitan Area', 'Lithuania', 'Netherlands', 'Poland', 'Portugal', 'Prague Metropolitan Area', 'Romania', 'Rotterdam and The Hague', 'Spain', 'Stuttgart Region', 'Warsaw Metropolitan Area', 'Wroclaw Metropolitan Area']

In [16]:
# заменим неявные дубликаты
replace_name(df,'country','Amsterdam Area','Netherlands')
replace_name(df,'country','Athens Metropolitan Area', 'Greece')
replace_name(df,'country','Berlin Metropolitan Area', 'Germany')
replace_name(df,'country','Brussels Metropolitan Area', 'Belgium')
replace_name(df,'country','Cologne Bonn Region', 'Germany')
replace_name(df,'country','Copenhagen Metropolitan Area', 'Denmark')
replace_name(df,'country','Eindhoven Area', 'Netherlands')
replace_name(df,'country','Greater Banska Bystrica Area', 'Slovakia')
replace_name(df,'country','Greater Barcelona Metropolitan Area', 'Spain')
replace_name(df,'country','Greater Dijon Area', 'France')
replace_name(df,'country','Greater Lyon Area', 'France')
replace_name(df,'country','Greater Madrid Metropolitan Area', 'Spain')
replace_name(df,'country','Greater Milan Metropolitan Area', 'Italy')
replace_name(df,'country','Greater Munich Metropolitan Area', 'Germany')
replace_name(df,'country','Greater Munster Area', 'Ireland')
replace_name(df,'country','Greater Nuremberg Metropolitan Area', 'Germany')
replace_name(df,'country','Greater Oslo Region', 'Norway')
replace_name(df,'country','Greater Palma de Mallorca Metropolitan Area', 'Spain')
replace_name(df,'country','Greater Paris Metropolitan Region','France')
replace_name(df,'country','Greater Pau Area','France')
replace_name(df,'country','Greater Verona Metropolitan Area', 'Italy')
replace_name(df,'country','Iasi Metropolitan Area', 'Romania')
replace_name(df,'country','Krakow Metropolitan Area', 'Poland')
replace_name(df,'country','Lisbon Metropolitan Area', 'Portugal')
replace_name(df,'country','Prague Metropolitan Area', 'Czechia')
replace_name(df,'country','Rotterdam and The Hague', 'Netherlands')
replace_name(df,'country','Stuttgart Region', 'Germany')
replace_name(df,'country','Warsaw Metropolitan Area', 'Poland')
replace_name(df,'country','Wroclaw Metropolitan Area', 'Poland')
replace_name(df,'country',' ', '')
replace_name(df,'country','UnitedKingdom', 'United Kingdom')

In [17]:
# выведем уникальные значения для поиска неявных дубликатов
duplicated_column('country')

['Austria', 'Belgium', 'Bulgaria', 'Croatia', 'Czechia', 'Denmark', 'Estonia', 'Finland', 'France', 'Germany', 'Greece', 'Hungary', 'Ireland', 'Italy', 'Latvia', 'Lithuania', 'Luxembourg', 'Malta', 'Monaco', 'Netherlands', 'Norway', 'Poland', 'Portugal', 'Romania', 'Slovakia', 'Spain', 'Sweden', 'Switzerland', 'United Kingdom']

Столбец 'employment_type'

In [18]:
# выведем уникальные значения для поиска неявных дубликатов

duplicated_column('employment_type')

['Hybrid', 'On-site', 'Remote', 'not specified']

Столбец 'employee_qty'

In [19]:
# выведем уникальные значения для поиска неявных дубликатов

duplicated_column('employee_qty')

['1,001-5,000 employees', '1-10 employees', '10,001+ employees', '11-50 employees', '201-500 employees', '5,001-10,000 employees', '501-1,000 employees', '51-200 employees', 'Retail Apparel and Fashion', 'Romain GUIHENEUF is hiring for this job', 'See how you compare to 10 applicants. Try Premium for free', 'See how you compare to 13 applicants. Try Premium for free', 'See how you compare to 19 applicants. Try Premium for free', 'See how you compare to 22 applicants. Try Premium for free', 'See how you compare to 4 applicants. Try Premium for free', 'See how you compare to 9 applicants. Try Premium for free', 'See recent hiring trends for Devonshire Hayes Recruitment Specialists Ltd. Try Premium for free', 'Svein Grande is hiring for this job', 'not specified']

In [20]:
# заменим "See how you compare to ... applicants. Try Premium for free",
# "See recent hiring trends for Devonshire Hayes Recruitment Specialists Ltd. Try Premium for free",
# "Svein Grande is hiring for this job",
# "Romain GUIHENEUF is hiring for this job" и
# "Retail Apparel and Fashion" (дублирование из столбца на company_field) на "not specified",
# поскольку это то же самое, что "не указано"

replace_name(df,'employee_qty','See how you compare to 10 applicants. Try Premium for free','not specified')
replace_name(df,'employee_qty','See how you compare to 13 applicants. Try Premium for free','not specified')
replace_name(df,'employee_qty','See how you compare to 19 applicants. Try Premium for free','not specified')
replace_name(df,'employee_qty','See how you compare to 22 applicants. Try Premium for free','not specified')
replace_name(df,'employee_qty','See how you compare to 4 applicants. Try Premium for free','not specified')
replace_name(df,'employee_qty','See how you compare to 9 applicants. Try Premium for free','not specified')
replace_name(df,'employee_qty','See recent hiring trends for Devonshire Hayes Recruitment Specialists Ltd. Try Premium for free',\
             'not specified')
replace_name(df,'employee_qty','Svein Grande is hiring for this job','not specified')
replace_name(df,'employee_qty','Romain GUIHENEUF is hiring for this job','not specified')
replace_name(df,'employee_qty','Retail Apparel and Fashion','not specified')

In [21]:
# проверим, что замена осуществлена

duplicated_column('employee_qty')

['1,001-5,000 employees', '1-10 employees', '10,001+ employees', '11-50 employees', '201-500 employees', '5,001-10,000 employees', '501-1,000 employees', '51-200 employees', 'not specified']

Столбец company_field

In [22]:
# выведем уникальные значения для поиска неявных дубликатов
duplicated_column('company_field')

['1,001-5,000 employees', '1-10 employees', '11-50 employees', '201-500 employees', '501-1,000 employees', '51-200 employees', 'Advertising Services', 'Airlines and Aviation', 'Apparel & Fashion', 'Appliances, Electrical, and Electronics Manufacturing', 'Armed Forces', 'Automation Machinery Manufacturing', 'Automotive', 'Aviation and Aerospace Component Manufacturing', 'Banking', 'Biotechnology Research', 'Book and Periodical Publishing', 'Business Consulting and Services', 'Chemical Manufacturing', 'Computer Games', 'Computer and Network Security', 'Computers and Electronics Manufacturing', 'Construction', 'Consumer Goods', 'Consumer Services', 'Cosmetics', 'Dairy Product Manufacturing', 'Defense & Space', 'Defense and Space Manufacturing', 'Education Administration Programs', 'Entertainment Providers', 'Environmental Services', 'Farming', 'Financial Services', 'Food & Beverages', 'Food Production', 'Food and Beverage Manufacturing', 'Food and Beverage Services', 'Gambling Facilities and Casinos', 'Glass, Ceramics and Concrete Manufacturing', 'Government Administration', 'Higher Education', 'Hospitality', 'Hospitals and Health Care', 'Human Resources', 'Human Resources Services', 'IT Services and IT Consulting', 'Individual and Family Services', 'Industrial Machinery Manufacturing', 'Information Services', 'Information Technology & Services', 'Insurance', 'International Affairs', 'International Trade and Development', 'Internet Marketplace Platforms', 'Internet Publishing', 'Investment Banking', 'Investment Management', 'Law Enforcement', 'Law Practice', 'Leisure, Travel & Tourism', 'Machinery Manufacturing', 'Manufacturing', 'Market Research', 'Mechanical Or Industrial Engineering', 'Medical Equipment Manufacturing', 'Mental Health Care', 'Motor Vehicle Manufacturing', 'Motor Vehicle Parts Manufacturing', 'Musicians', 'Newspaper Publishing', 'Non-profit Organizations', 'Oil and Gas', 'Outsourcing and Offshoring Consulting', 'Packaging and Containers Manufacturing', 'Performing Arts', 'Personal Care Product Manufacturing', 'Pharmaceutical Manufacturing', 'Philanthropic Fundraising Services', 'Primary Metal Manufacturing', 'Printing Services', 'Professional Services', 'Public Relations and Communications Services', 'Railroad Equipment Manufacturing', 'Real Estate', 'Renewable Energy Power Generation', 'Renewable Energy Semiconductor Manufacturing', 'Research', 'Research Services', 'Restaurants', 'Retail', 'Retail Apparel and Fashion', 'Retail Groceries', 'Retail Health and Personal Care Products', 'Retail Luxury Goods and Jewelry', 'Retail Office Equipment', 'Romain GUIHENEUF is hiring for this job', 'See how you compare to 10 applicants. Try Premium for free', 'See how you compare to 13 applicants. Try Premium for free', 'See how you compare to 19 applicants. Try Premium for free', 'See how you compare to 22 applicants. Try Premium for free', 'See how you compare to 4 applicants. Try Premium for free', 'See how you compare to 9 applicants. Try Premium for free', 'See recent hiring trends for Devonshire Hayes Recruitment Specialists Ltd. Try Premium for free', 'Semiconductor Manufacturing', 'Software Development', 'Spectator Sports', 'Sporting Goods Manufacturing', 'Staffing and Recruiting', 'Svein Grande is hiring for this job', 'Technology, Information and Internet', 'Telecommunications', 'Translation and Localization', 'Transportation, Logistics, Supply Chain and Storage', 'Travel Arrangements', 'Truck Transportation', 'Utilities', 'Wellness and Fitness Services', 'Wholesale', 'Wholesale Building Materials', 'Wind Electric Power Generation', 'not specified']

Видим, что в данном столбце есть значения, которые не соответствуют сути данного столбца (про количество сотрудников). Прежде чем убирать эти данные, проверим, что в столбце employee_qty все заполнено

In [23]:
# убеждаемся, что в столбце employee_qty все заполнено
df[(df['company_field'] == '1,001-5,000 employees')|(df['company_field'] == '1-10 employees')|\
   (df['company_field'] == '11-50 employees')|(df['company_field'] == '201-500 employees')|\
   (df['company_field'] == '501-1,000 employees')|(df['company_field'] == '51-200 employees')]

,title,location,country,employment_type,company_name,employee_qty,company_field,skills,job_description,applicants
34,Data Analyst,Vilnius,Lithuania,Hybrid,Havas Group Lithuania,51-200 employees,51-200 employees,"<span class=""visually-hidden""><!-- -->Skills: ...",What You Will Do...,98.0
44,Data Analyst,Milan,Italy,Hybrid,SPIN 360,11-50 employees,11-50 employees,"<span class=""visually-hidden""><!-- -->Skills: ...",About the Compan...,196.0
49,Data Analyst,France,France,Remote,Hubble_s,11-50 employees,11-50 employees,"<span class=""visually-hidden""><!-- -->Skills: ...",Data Analyst - I...,0.0
58,Consultor BI,Barcelona,Spain,Hybrid,Konozca Consulting,11-50 employees,11-50 employees,"<span class=""visually-hidden""><!-- -->Skills: ...",Konozca crece y...,86.0
61,Data Analyst,Hungary,Hungary,Remote,Peroptyx,11-50 employees,11-50 employees,"<span class=""visually-hidden""><!-- -->Skills: ...",For thousands of ...,177.0
137,Data analyst,Bordeaux,France,Hybrid,RH Partners,51-200 employees,51-200 employees,"<span class=""visually-hidden""><!-- -->Skills: ...",Notre client est ...,0.0
258,Data Analyst (m/w/d),Düsseldorf,Germany,On-site,Benchmark International,201-500 employees,201-500 employees,"<span class=""visually-hidden""><!-- -->Skills: ...",Über uns: Mit...,102.0
282,Data Governance analyst,Vilvoorde,Belgium,On-site,Streamz,201-500 employees,201-500 employees,"<span class=""visually-hidden""><!-- -->Skills: ...",Streamz is de Vla...,4.0
355,Datový analytik/vývojář,Prague Metropolitan Area,Czechia,Hybrid,Direct technologies,51-200 employees,51-200 employees,"<span class=""visually-hidden""><!-- -->Skills: ...",Hledáme data ana...,4.0
401,Data Analist - startersfunctie (Dutch speaking),The Hague,Netherlands,Hybrid,Whooz,11-50 employees,11-50 employees,"<span class=""visually-hidden""><!-- -->Skills: ...","Van leuk werk, k...",19.0
452,Junior project manager - Categoria Protetta,Milan,Italy,Hybrid,BluCRM,51-200 employees,51-200 employees,"<span class=""visually-hidden""><!-- -->Skills: ...",Chi siamo Siam...,14.0
453,Junior Business Analyst,Lombardy,Italy,On-site,Consulcesi Group,"501-1,000 employees","501-1,000 employees","<span class=""visually-hidden""><!-- -->Skills: ...",Within the SAR D...,97.0
454,Softwareentwickler (m/w/d),Coburg,Germany,Hybrid,KAPP NILES,"1,001-5,000 employees","1,001-5,000 employees","<span class=""visually-hidden""><!-- -->Skills: ...",KAPP NILES ist ei...,19.0
473,Medewerker verkoop binnendienst,Doesburg,Netherlands,On-site,Wigersma & Sikkema B.V.,11-50 employees,11-50 employees,"<span class=""visually-hidden""><!-- -->Skills: ...",Wigersma &amp; Si...,1.0
474,BÜROKRAFT (M/W/D) IN GARCHING,Munich,Germany,On-site,FITCOMPANY GmbH,201-500 employees,201-500 employees,"<span class=""visually-hidden""><!-- -->Skills: ...",Aufgabenbereich ...,8.0
475,Mitarbeiter Marketing (m/w/d),Tussenhausen,Germany,On-site,RUF Briquetting Systems,51-200 employees,51-200 employees,"<span class=""visually-hidden""><!-- -->Skills: ...",WERDE TEIL DER RUF...,9.0
477,Ingenieur Softwareentwicklung (m/w/d),Hückelhoven,Germany,Hybrid,HUBER+SUHNER BKtel GmbH,51-200 employees,51-200 employees,"<span class=""visually-hidden""><!-- -->Skills: ...",Wir suchen an uns...,22.0
478,Projektmanager / Projektleiter Automotive (m/w/d),Eisenach,Germany,Hybrid,REBO Lighting & Electronics GmbH,201-500 employees,201-500 employees,"<span class=""visually-hidden""><!-- -->Skills: ...",Wir suchen Dich a...,25.0
479,ESG Analyst - Real Estate (m/w/d),Luxembourg,Luxembourg,On-site,Empira Group,201-500 employees,201-500 employees,"<span class=""visually-hidden""><!-- -->Skills: ...",Empira Investment...,42.0
480,APM Software Development & Operations,Berlin,Germany,Hybrid,Perform IT,51-200 employees,51-200 employees,"<span class=""visually-hidden""><!-- -->Skills: ...",Who are Perform ...,68.0
481,Accountant,Stockholm County,Sweden,Remote,HansaWorld,201-500 employees,201-500 employees,"<span class=""visually-hidden""><!-- -->Skills: ...",Join us to become...,146.0
483,Mitarbeiter Marketing B2B (m/w/d),Munich,Germany,Hybrid,Simovative,51-200 employees,51-200 employees,"<span class=""visually-hidden""><!-- -->Skills: ...",This job is...,32.0
484,Chargé de projets Sustainability F/H en appren...,Erstein,France,On-site,WURTH INDUSTRIE FRANCE,51-200 employees,51-200 employees,"<span class=""visually-hidden""><!-- -->Skills: ...",WÜRTH INDUSTRIE ...,54.0
485,Test Engineer,Szombathely,Hungary,On-site,Ivy Technology,"1,001-5,000 employees","1,001-5,000 employees","<span class=""visually-hidden""><!-- -->Skills: ...",Built on a founda...,13.0
486,Systemutvecklare,Ronneby,Sweden,On-site,NovaCast Systems,11-50 employees,11-50 employees,"<span class=""visually-hidden""><!-- -->Skills: ...",Systemutvecklare...,16.0
487,IT-Spezialist (m/w/d),Elmshorn,Germany,Hybrid,Teppich-Kibek,"501-1,000 employees","501-1,000 employees","<span class=""visually-hidden""><!-- -->Skills: ...",Wie wird aus eine...,8.0
489,Projektleitung Seiltechnik,Bremen,Germany,On-site,Gleistein GmbH,201-500 employees,201-500 employees,"<span class=""visually-hidden""><!-- -->Skills: ...","Hast du den Mut,...",40.0
490,Säljare till Skaraborgsområdet,Lidköping,Sweden,Hybrid,Linde Material Handling Sverige,201-500 employees,201-500 employees,"<span class=""visually-hidden""><!-- -->Skills: ...",Brinner du för ...,4.0
491,Medewerker Cursuscoördinatie,Ede,Netherlands,Hybrid,ROVC Technische Opleidingen,51-200 employees,51-200 employees,"<span class=""visually-hidden""><!-- -->Skills: ...",Als medewerker c...,1.0
492,Chef de Projet Réhabilitation,Rouen,France,On-site,CORHEME,1-10 employees,1-10 employees,"<span class=""visually-hidden""><!-- -->Skills: ...",Poste : Chef de ...,24.0
497,Reporting Specialist,Tallinn,Estonia,Hybrid,BaltCap,11-50 employees,11-50 employees,"<span class=""visually-hidden""><!-- -->Skills: ...",Your main role a...,15.0
498,Product Manager,Amsterdam,Netherlands,Hybrid,Spinnin'​ Records,51-200 employees,51-200 employees,"<span class=""visually-hidden""><!-- -->Skills: ...",ABOUT SPINNIN’ ...,115.0
499,"IT Support Analyst, Global IT",Farum,Denmark,On-site,Danelec,51-200 employees,51-200 employees,"<span class=""visually-hidden""><!-- -->Skills: ...",Do you have a pa...,12.0
508,Chemical development process Lab analyst,Braine-l’Alleud,Belgium,On-site,Eurofins PSS Insourcing Solutions,"1,001-5,000 employees","1,001-5,000 employees","<span class=""visually-hidden""><!-- -->Skills: ...",Company Descrip...,62.0
509,DATA ANALYST IT,Vila Nova de Cerveira,Portugal,On-site,Potenzia Consultores,1-10 employees,1-10 employees,"<span class=""visually-hidden""><!-- -->Skills: ...","O nosso cliente, ...",17.0
515,Composiet medewerker,Lelystad,Netherlands,On-site,Stratos Yacht,1-10 employees,1-10 employees,"<span class=""visually-hidden""><!-- -->Skills: ...",Stratos Yacht B....,2.0
520,Sales Specialist,Marsa,Malta,On-site,Yellow Malta,11-50 employees,11-50 employees,"<span class=""visually-hidden""><!-- -->Skills: ...",Yellow Malta woul...,63.0
533,System Developer GIS,Åre,Sweden,Hybrid,Sunna Group,1-10 employees,1-10 employees,"<span class=""visually-hidden""><!-- -->Skills: ...",Vill Du bidra til...,28.0
534,Analista de Software,Bilbao-Bilbo,Spain,Hybrid,Deusto SEIDOR,51-200 employees,51-200 employees,"<span class=""visually-hidden""><!-- -->Skills: ...","GRUPO SEIDOR, Mul...",32.0
584,Data Engineer,Porto,Portugal,Hybrid,BrandDelta,11-50 employees,11-50 employees,"<span class=""visually-hidden""><!-- -->Skills: ...",Company Descript...,43.0
624,Data Specialist,Athens Metropolitan Area,Greece,Hybrid,Modelity Technologies,51-200 employees,51-200 employees,"<span class=""visually-hidden""><!-- -->Skills: ...",Job summary A...,116.0
630,Data Scientist,Prague,Czechia,Hybrid,Gauss & Neumann,11-50 employees,11-50 employees,"<span class=""visually-hidden""><!-- -->Skills: ...",At Gauss &amp; Ne...,139.0
648,Business Intelligence Engineer,Palaión Fáliron,Greece,On-site,Altair Travel Agency S.A. - Tripair GmbH,51-200 employees,51-200 employees,"<span class=""visually-hidden""><!-- -->Skills: ...",Responsibilities:...,11.0
659,Data Scientist,Finland,Finland,Remote,Centre for Research on Energy and Clean Air (C...,1-10 employees,1-10 employees,"<span class=""visually-hidden""><!-- -->Skills: ...",CREA ( Centre for...,182.0
665,Data Engineer,Madrid,Spain,Hybrid,El Cactus,1-10 employees,1-10 employees,"<span class=""visually-hidden""><!-- -->Skills: ...",DATA ENGINEER ...,60.0
698,Information Technology Support Specialist,Greater Oslo Region,Norway,On-site,Oslo International School,51-200 employees,51-200 employees,"<span class=""visually-hidden""><!-- -->Skills: ...",IT SUPPORT SPECI...,98.0
730,Information Technology Engineer,Piraeus,Greece,On-site,Piraeus Port Authority-PPA/OLP-COSCO Shipping,"1,001-5,000 employees","1,001-5,000 employees","<span class=""visually-hidden""><!-- -->Skills: ...",Job description ...,77.0
797,Analista funzionale,Pordenone,Italy,On-site,Magia Srl,11-50 employees,11-50 employees,"<span class=""visually-hidden""><!-- -->Skills: ...",Magia S.r.l. è ...,30.0
798,Programmatore / Analista funzionale,Turin,Italy,Hybrid,Zanichelli editore S.p.A,201-500 employees,201-500 employees,"<span class=""visually-hidden""><!-- -->Skills: ...",Siamo alla ricerc...,87.0
822,Analista funzionale,Pordenone,Italy,On-site,Magia Srl,11-50 employees,11-50 employees,"<span class=""visually-hidden""><!-- -->Skills: ...",Magia S.r.l. è ...,30.0
824,Chargé de projet validation stérilisation,Bernay,France,On-site,Steriservices,51-200 employees,51-200 employees,None,Dans le but de re...,38.0
837,Front-end Developer,Porto,Portugal,Hybrid,Fraunhofer Portugal AICOS,51-200 employees,51-200 employees,"<span class=""visually-hidden""><!-- -->Skills: ...",Job Title: Fr...,126.0
874,Mid Data Engineer,Portugal,Portugal,Remote,Scotty Technologies,11-50 employees,11-50 employees,"<span class=""visually-hidden""><!-- -->Skills: ...",Hey! We are Scott...,94.0
903,Data Scientist,Milan,Italy,Hybrid,CGnal,11-50 employees,11-50 employees,"<span class=""visually-hidden""><!-- -->Skills: ...",The role of Data ...,117.0
975,Database Administrator,Porto,Portugal,On-site,AIMS International Spain,11-50 employees,11-50 employees,"<span class=""visually-hidden""><!-- -->Skills: ...",Our client -DR. ...,21.0
977,Process Performance Engineer,Amsterdam,Netherlands,Hybrid,Tony's Chocolonely,51-200 employees,51-200 employees,"<span class=""visually-hidden""><!-- -->Skills: ...",At Tony’s Chocolo...,73.0
981,Data Engineer,Copenhagen Metropolitan Area,Denmark,On-site,Radiobotics,11-50 employees,11-50 employees,"<span class=""visually-hidden""><!-- -->Skills: ...",Are you a data ...,44.0
997,Analista de datos BI,Valencia,Spain,Hybrid,Infoport,51-200 employees,51-200 employees,None,Funciones · Bu...,198.0

In [24]:
# заменим данные из данного столбца с данными о количестве сотрудников на 'not specified'
replace_name(df,'company_field','1,001-5,000 employees','not specified')
replace_name(df,'company_field','1-10 employees','not specified')
replace_name(df,'company_field','11-50 employees','not specified')
replace_name(df,'company_field','201-500 employees','not specified')
replace_name(df,'company_field','501-1,000 employees','not specified')
replace_name(df,'company_field','51-200 employees','not specified')

In [25]:
# заменим See how you compare to ... applicants. Try Premium for free и 
# Romain GUIHENEUF is hiring for this job на not specified и т.д.

replace_name(df,'company_field','See how you compare to 10 applicants. Try Premium for free','not specified')
#replace_name('employee_qty',list_name,'not specified')
replace_name(df,'company_field','See how you compare to 13 applicants. Try Premium for free','not specified')
replace_name(df,'company_field','See how you compare to 19 applicants. Try Premium for free','not specified')
replace_name(df,'company_field','See how you compare to 22 applicants. Try Premium for free','not specified')
replace_name(df,'company_field','See how you compare to 4 applicants. Try Premium for free','not specified')
replace_name(df,'company_field','See how you compare to 9 applicants. Try Premium for free','not specified')
replace_name(df,'company_field','See recent hiring trends for Devonshire Hayes Recruitment Specialists Ltd. Try Premium for free',\
             'not specified')
replace_name(df,'company_field','Svein Grande is hiring for this job','not specified')
replace_name(df,'company_field','Romain GUIHENEUF is hiring for this job','not specified')

In [26]:
# проверим, что замена произошла
duplicated_column('company_field')

['Advertising Services', 'Airlines and Aviation', 'Apparel & Fashion', 'Appliances, Electrical, and Electronics Manufacturing', 'Armed Forces', 'Automation Machinery Manufacturing', 'Automotive', 'Aviation and Aerospace Component Manufacturing', 'Banking', 'Biotechnology Research', 'Book and Periodical Publishing', 'Business Consulting and Services', 'Chemical Manufacturing', 'Computer Games', 'Computer and Network Security', 'Computers and Electronics Manufacturing', 'Construction', 'Consumer Goods', 'Consumer Services', 'Cosmetics', 'Dairy Product Manufacturing', 'Defense & Space', 'Defense and Space Manufacturing', 'Education Administration Programs', 'Entertainment Providers', 'Environmental Services', 'Farming', 'Financial Services', 'Food & Beverages', 'Food Production', 'Food and Beverage Manufacturing', 'Food and Beverage Services', 'Gambling Facilities and Casinos', 'Glass, Ceramics and Concrete Manufacturing', 'Government Administration', 'Higher Education', 'Hospitality', 'Hospitals and Health Care', 'Human Resources', 'Human Resources Services', 'IT Services and IT Consulting', 'Individual and Family Services', 'Industrial Machinery Manufacturing', 'Information Services', 'Information Technology & Services', 'Insurance', 'International Affairs', 'International Trade and Development', 'Internet Marketplace Platforms', 'Internet Publishing', 'Investment Banking', 'Investment Management', 'Law Enforcement', 'Law Practice', 'Leisure, Travel & Tourism', 'Machinery Manufacturing', 'Manufacturing', 'Market Research', 'Mechanical Or Industrial Engineering', 'Medical Equipment Manufacturing', 'Mental Health Care', 'Motor Vehicle Manufacturing', 'Motor Vehicle Parts Manufacturing', 'Musicians', 'Newspaper Publishing', 'Non-profit Organizations', 'Oil and Gas', 'Outsourcing and Offshoring Consulting', 'Packaging and Containers Manufacturing', 'Performing Arts', 'Personal Care Product Manufacturing', 'Pharmaceutical Manufacturing', 'Philanthropic Fundraising Services', 'Primary Metal Manufacturing', 'Printing Services', 'Professional Services', 'Public Relations and Communications Services', 'Railroad Equipment Manufacturing', 'Real Estate', 'Renewable Energy Power Generation', 'Renewable Energy Semiconductor Manufacturing', 'Research', 'Research Services', 'Restaurants', 'Retail', 'Retail Apparel and Fashion', 'Retail Groceries', 'Retail Health and Personal Care Products', 'Retail Luxury Goods and Jewelry', 'Retail Office Equipment', 'Semiconductor Manufacturing', 'Software Development', 'Spectator Sports', 'Sporting Goods Manufacturing', 'Staffing and Recruiting', 'Technology, Information and Internet', 'Telecommunications', 'Translation and Localization', 'Transportation, Logistics, Supply Chain and Storage', 'Travel Arrangements', 'Truck Transportation', 'Utilities', 'Wellness and Fitness Services', 'Wholesale', 'Wholesale Building Materials', 'Wind Electric Power Generation', 'not specified']

**Вывод:**
- в столбцах company_field, employee_qty и country произведена замена неявных дубликатов

**Создание новой таблицы, где вакансии будут только в сфере Дата аналитики и Дата сайнтса**

In [27]:
# приведем к нижнему регистру значения столбцов (job_description, skills) для упрощения работы с ними 
# (для вычленения хард скиллов)

def lowers(i):
    df[i] = df[i].str.lower()

In [28]:
lowers('job_description')
lowers('skills')
lowers('title')

In [29]:
# создадим новую таблицу, где будут данные только по дата аналитикам и дата сайнтистам

df_new = df.loc[df['title'].str.contains('anal') | df['title'].str.contains('scient')]

In [30]:
data.shape[0]

998

**Проверка на количества оставшихся данных**

In [31]:
print('Было {a} строк, стало {b} строк, что составляет {c:.2%} от изначального количества'.format(a = data.shape[0],\
                                                                                            b = df_new.shape[0],\
                                                                                            c = df_new.shape[0]/data.shape[0]))

Было 998 строк, стало 807 строк, что составляет 80.86% от изначального количества

**Вывод:**
- осталось 81% от изначального объема.

**Скорректируем индексы после фильтрации и выведение их в качества столбца для идентификации вакансии**

In [32]:
# корректировка индексов с удалением старых индексов и создание столбца с новыми индексами
df_new = df_new.reset_index(drop=True)#.reset_index()
df_new = df_new.reset_index().rename(columns = {'index':'number_vacancy'})

# проверка
df_new.tail(5)

,number_vacancy,title,location,country,employment_type,company_name,employee_qty,company_field,skills,job_description,applicants
802,802,marketing analyst,Vilnius,Lithuania,Hybrid,Avon,"10,001+ employees",Personal Care Product Manufacturing,"<span class=""visually-hidden""><!-- -->skills: ...",you’ve picked a gr...,73.0
803,803,emerton data: data scientist & strategy consul...,Paris,France,Hybrid,Emerton,51-200 employees,Business Consulting and Services,"<span class=""visually-hidden""><!-- -->skills: ...",visit: emerton-d...,188.0
804,804,stage | data analyst,Vermezzo,Italy,Hybrid,CPM Italy,51-200 employees,Retail,"<span class=""visually-hidden""><!-- -->skills: ...",this job is...,0.0
805,805,business-analyst:in,Greater Munich Metropolitan Area,Germany,Hybrid,Computer Futures,"501-1,000 employees",IT Services and IT Consulting,"<span class=""visually-hidden""><!-- -->skills: ...",do you want to wo...,51.0
806,806,analista de datos bi,Valencia,Spain,Hybrid,Infoport,51-200 employees,not specified,none,funciones · bu...,198.0

**Выделение хард скиллов**

In [33]:
# создадим список с перечнем хард скиллов, которые будут вычленяться из столбца job_description
skills = [
    ' a/b testing', ' ab testing', ' actian', ' adobe analytics', ' adobe audience manager ',
    ' adobe experience platform', ' adobe launch ', ' adobe target ', ' ai ', 'airflow ',
    ' alooma ', ' alteryx', ' amazon machine learning ', ' amazon web services ', ' aml ',
    ' amplitude ', ' ansible ', ' apache camel ', ' apache nifi ', ' apache spark ',
    ' api ', ' asana ', ' auth0 ', ' aws ', ' aws glue ', ' azure ', ' azure data factory ',
    ' basecamp', ' bash', ' beats ', ' big query ', ' bigquery ', ' birst', ' bitbucket',
    ' blendo ', ' bootstrap ', ' business objects bi ', ' c# ', ' c++ ', ' caffe ', ' cassandra ',
    ' cdata sync', ' chronograf ', ' ci/cd ', ' cicd ', ' clickhouse ', ' cloudera ', ' cluvio ',
    ' cntk ', ' cognos', ' composer ', ' computer vision ', ' conda', ' confluence ',
    ' couchbase ', ' css ', ' d3.js ', ' dash ', ' dashboard ', ' data factory ', ' data fusion ',
    ' data mining ', ' data studio ', ' data warehouse ', ' databricks ', ' dataddo ',
    ' dataflow ', ' datahub', ' dataiku ', ' datastage ', ' dbconvert ', ' dbeaver ', ' dbt ',
    ' deep learning ', ' dl/ml', ' docker ', 'domo ', ' dune ', ' dv360 ', ' dynamodb ',
    ' elasticsearch ', ' elt ', ' erwin ', ' etl ', ' etleap', ' excel ', 'facebook business manager ',
    ' fivetran ', ' fuzzy ', ' ga360 ', ' gcp ', ' gensim ', ' ggplot ', ' git ', ' github ', ' gitlab ',
    ' google ads ', ' google analytics ', ' google cloud platform ', ' google data flow ',
    ' google optimize ', ' google sheets ', ' google tag manager ', ' google workspace ',
    ' grafana ', ' hadoop', ' hana ', ' hanagrafana ', 'hbase ', ' hdfs ', ' hevo data ', ' hightouch ',
    ' hive ', ' hivedatabricks ', ' html ', ' hubspot ', ' ibm coremetrics ', ' inetsoft ',
    ' influxdb ', 'informatica ', ' integrate.io ', ' iri voracity ', ' izenda ', ' java ',
    ' java script ', 'javascript', 'jenkins', 'jira', ' jmp ', ' julia ', 'jupyter',
    ' k2view ', ' kafka ', ' kantar ', ' kapacitor ', ' keras ', ' kibana ', ' kubernetes ',
    ' lambda ', ' linux ', ' logstash ', ' looker ', ' lstm ', ' luidgi ', ' matillion ', ' matlab ',
    ' matplotlib ', ' mendix ', ' metabase ', ' microsoft sql ', ' microsoft sql server ',
    ' microstrategy ', ' miro ', ' mixpanel ', ' ml ', ' ml flow ', ' mlflow ', ' mongodb ', ' mxnet ',
    ' mysql ', ' natural nanguage processing ', ' neo4j ', ' nlp ', ' nltk ', ' nosql ', ' numpy ',
    ' oauth ', 'octave', ' omniture ', ' omnituregitlab ', ' openshift ', ' openstack ',
    ' optimizely ', ' oracle ', '  oracle business intelligence ', ' oracle data integrator ',
    ' pandas ', ' panorama ', ' pentaho ', ' plotly ', ' postgre ', ' postgresql ', ' posthog ',
    ' power amc ', ' power bi ', 'power point', 'powerbi', 'powerpivot', ' powerpoint ',
    ' powerquery ', ' pyspark ', 'python ', 'pytorch', 'pytorchhevo data', ' qlik ',
    ' qlik sense ', ' qliksense ', ' qlikview ',' qlikview ', ' querysurge ', ' r ', ' raphtory ', ' rapidminer ', ' redash ',
    ' redis ', 'redshift ', 'retool', 'rivery', 'rust', 's3', 'sa360', 'salesforce', ' sap ',
    ' sap business objects ', ' sas ', ' sas visual analytics ', ' scala ', ' scikit-learn ',
    ' scipy ', ' seaborn ', ' segment ', ' selenium ', ' sem rush ', ' semrush ', ' shell ', ' shiny ',
    ' singer ', ' sisense ', ' skyvia ', ' snowflake ', ' spacy ', ' spark ', ' sparkml ', ' splunk ',
    ' spotfire ', ' spreadsheet ', ' spss ', ' sql ', ' ssis ', ' sssr ', ' stambia ', ' statistics ',
    ' statsbot ', ' stitch ', ' streamlit ', ' streamsets ', ' svn ', ' t-sql ', ' tableau ', ' talend ',
    ' targit ', ' tealium ', ' telegraf ', ' tensorflow ', 'terraapi ', 'terraform ', 'theano ',
    ' thoughtspot ', ' timeseries', 'trello ', ' unix ', ' vba ', '  vtom ', ' webfocus ', ' wfh ',
    ' xplenty ', ' xtract.io ', ' yellowfin ', ' английский язык ', ' english language ', ' french language ',
    ' французский язык ', ' немецкий язык ', ' german language '
]

In [34]:
# создадим функцию для вычленения хард-скиллов из столбца job_description
def skill_func(cell):
    skill_list = []
    for i in skills:
        if i in cell:
            skill_list.append(i)
    return skill_list

In [35]:
# выполним функцию для вычленения хард скиллов из столбца job_description 
# и создадим новый столбец из этих скиллов

df_new['job_skills_des'] = df_new['job_description'].apply(skill_func)

In [36]:
# создадим фунекцию для вычленения хард-скиллов из столбца skills

skill_list1 = []
for i in df_new['skills']:
    skill_list1.append(i.split(':')[-1].strip().split(',')[:2])

In [37]:
# создадим новый столбец с хард-скиллами из столбва skills

df_new['skills_1'] = skill_list1
df_new['skills_1']

0                                           [none]
1                                           [none]
2                                           [none]
3                                           [none]
4                                           [none]
                          ...
802    [marketing campaigns,  marketing reporting]
803                       [python,  решение задач]
804         [data analytics,  визуализация данных]
805         [аналитические навыки,  немецкий язык]
806                                         [none]
Name: skills_1, Length: 807, dtype: object

In [38]:
# объединим вычлененные хард скиллы

df_new["job_skills"] = df_new["job_skills_des"] + df_new["skills_1"]

In [39]:
# проверим, что хард скиллы вычленены из столбцов job_description и job_skills 
# и информация по ним объединена в столбце job_skills

df_new[['job_skills_des','skills_1','job_skills']].head(5)

,job_skills_des,skills_1,job_skills
0,"[ data mining , sap , sas , statistics ]",[none],"[ data mining , sap , sas , statistics , none]"
1,[],[none],[none]
2,[],[none],[none]
3,[ excel ],[none],"[ excel , none]"
4,"[ data warehouse , etl , oracle , python , ...",[none],"[ data warehouse , etl , oracle , python , ..."

In [40]:
# с помощью функции explode разобьем списки хард скиллов на отдельные хард скиллы для корректного анализа

df_new_explode = df_new.explode("job_skills")

In [41]:
# посмотрим на количеству уникальных вакансий 

df_new_explode['number_vacancy'].nunique()

807

In [42]:
# удалим столбцы со списками job_skills_des и job_skills_skil

In [43]:
del df_new_explode['job_skills_des']

In [44]:
del df_new_explode['skills_1']

In [45]:
# удалим строчки, в которых в столбце job_skills есть none
df_new_explode = df_new_explode.query('job_skills != "none"')

In [46]:
# удалим лишние проблемы
df_new_explode['job_skills'] = df_new_explode['job_skills'].str.strip()

In [47]:
#хард скиллы с похожими названиями и сутью объединим

replace_name(df_new_explode,'job_skills','ab testing','a/b testing')
replace_name(df_new_explode,'job_skills','java script','javascript')
replace_name(df_new_explode,'job_skills','pandas','python')
replace_name(df_new_explode,'job_skills','matplotlib','python')
replace_name(df_new_explode,'job_skills','seaborn','python')
replace_name(df_new_explode,'job_skills','numpy','python')
replace_name(df_new_explode,'job_skills','scipy','python')
replace_name(df_new_explode,'job_skills','plotly','python')
replace_name(df_new_explode,'job_skills','cicd','ci/cd')
replace_name(df_new_explode,'job_skills','postgre','sql')
replace_name(df_new_explode,'job_skills','postgresql','sql')
replace_name(df_new_explode,'job_skills','powerbi','power bi')
replace_name(df_new_explode,'job_skills','qlik sense','qlik')
replace_name(df_new_explode,'job_skills','qliksense','qlik')
replace_name(df_new_explode,'job_skills','qlikview','qlik')
replace_name(df_new_explode,'job_skills','qlik view','qlik')
replace_name(df_new_explode,'job_skills','big query','bigquery')
replace_name(df_new_explode,'job_skills','mysql','sql')
replace_name(df_new_explode,'job_skills','nosql','sql')
replace_name(df_new_explode,'job_skills','microsoft sql','microsoft sql server')
replace_name(df_new_explode,'job_skills','ml flow','mlflow')
replace_name(df_new_explode,'job_skills','aws glue','aws')
replace_name(df_new_explode,'job_skills','etl tools','etl')
replace_name(df_new_explode,'job_skills','a/b тестирование','a/b testing')
replace_name(df_new_explode,'job_skills','microsoft sql server server','microsoft sql server')
replace_name(df_new_explode,'job_skills','microsoft sql server server','microsoft sql server server')
replace_name(df_new_explode,'job_skills','microsoft sql server server server server','microsoft sql server')
replace_name(df_new_explode,'job_skills','microsoft sql server server server server server','microsoft sql server')
replace_name(df_new_explode,'job_skills','msql','sql')
replace_name(df_new_explode,'job_skills','powerpoint','power point')
replace_name(df_new_explode,'job_skills','sqlsql','sql')
replace_name(df_new_explode,'job_skills',' statutory accounting principles (sap) ','sap')
replace_name(df_new_explode,'job_skills','искусственный интеллект<!-- --></span>','ai')
replace_name(df_new_explode,'job_skills','visualization','визуализация данных')
replace_name(df_new_explode,'job_skills','microsoft excel','excel')
replace_name(df_new_explode,'job_skills','salesforce.com','salesforce')
replace_name(df_new_explode,'job_skills','english language','английский язык')
replace_name(df_new_explode,'job_skills','статистика','statistics')
replace_name(df_new_explode,'job_skills','машинное обучение','machine learning')
replace_name(df_new_explode,'job_skills','ml','machine learning')
replace_name(df_new_explode,'job_skills','machine learning algorithms','machine learning')
replace_name(df_new_explode,'job_skills','yellowfin','yellowfin bi')
replace_name(df_new_explode,'job_skills','yellowfin bi bi','yellowfin bi')
replace_name(df_new_explode,'job_skills','statistics по компании','statistics')
replace_name(df_new_explode,'job_skills','snowflake cloud','snowflake')
replace_name(df_new_explode,'job_skills','google bigquery','bigquery')
#replace_name(df_new_explode,'job_skills',' google cloud platform ','google cloud platform (gcp)')

In [48]:
# проверим таблицу на наличие дубликатов
df_new_explode.duplicated().sum()

197

In [49]:
# удалим явные дублированные строки и проверим, что их не осталось
df_new_explode = df_new_explode.drop_duplicates()

In [50]:
# проверим, что все дубликаты удалены
df_new_explode.duplicated().sum()

0

In [51]:
sorted(df_new_explode['job_skills'].unique())

['a/b testing',
 'abstracting',
 'ad hoc analysis',
 'adobe analytics',
 'adobe target',
 'agile software development',
 'ai',
 'airflow',
 'algorithm development',
 'alteryx',
 'amachine learning',
 'amazon elastic mapreduce (emr)',
 'amazon kinesis',
 'amazon quicksight',
 'amazon web services (aws)',
 'amplitude',
 'analytical modelling',
 'analytique',
 'apache kafka',
 'apache spark',
 'apache spark streaming',
 'api',
 'application services',
 'attention to detail',
 'attribution',
 'aws',
 'azure',
 'bash',
 'basque',
 'bigquery',
 'bitbucket',
 'bpmn',
 'budget tracking',
 'business administration',
 'business analysis',
 'business case development',
 'business case preparation',
 'business reviews',
 'business solution',
 'business support',
 'c#',
 'c++',
 'ci/cd',
 'clickhouse',
 'cloudera',
 'cluster analysis',
 'cognos',
 'commerce',
 'confluence',
 'coordinating skills',
 'crm',
 'cross-channel marketing',
 'cross-team collaboration',
 'css',
 'cultural affairs',
 'dash',
 'dashboard',
 'data analytics',
 'data engineering',
 'data feeds',
 'data governance',
 'data interpretation',
 'data manipulation',
 'data mining',
 'data pipelines',
 'data studio',
 'data warehouse',
 'data-driven decision making',
 'database queries',
 'databricks',
 'dataiku dss',
 'datastage',
 'dax',
 'dbt',
 'dcf valuation',
 'deep learning',
 'dhcp',
 'digital technology',
 'docker',
 'domo',
 'ecmascript',
 'elt',
 'enterprise service bus (esb) architecture',
 'environmental',
 'erd',
 'esprit',
 'etl',
 'excel',
 'factiva',
 'feature extraction',
 'fivetran',
 'french language',
 'futures',
 'gcp',
 'german language',
 'git',
 'github',
 'gitlab',
 'gmp (надлежащая производственная практика)',
 'google analytics',
 'google cloud platform',
 'google cloud platform (gcp)',
 'google data studio',
 'google sheets',
 'google tag manager',
 'google workspace',
 'hadoop',
 'hana',
 'high level of accuracy',
 'htmachine learning',
 'hubspot',
 'human behavior',
 'hyperion financial management (hfm)',
 'hypothesis testing',
 'industrial internet of things (iiot)',
 'informatica',
 'interpreting data',
 'it business analysis',
 'it solutions',
 'itil',
 'java',
 'javascript',
 'jenkins',
 'jira',
 'julia',
 'jupyter',
 'kafka',
 'keras',
 'kibana',
 'kubernetes',
 'lambda',
 'learning',
 'linux',
 'looker',
 'looker (software)',
 'machine learning',
 'marketing campaigns',
 'marketing mix modeling',
 'marketing reporting',
 'matillion',
 'matlab',
 'metabase',
 'metrics definition',
 'microsoft dynamics nav',
 'microsoft office',
 'microsoft power bi',
 'microsoft power query',
 'microsoft sql server',
 'microstrategy',
 'mixpanel',
 'mobile switching centre server (mss)',
 'moe',
 'mongodb',
 'new product rollout',
 'nlp',
 'oracle',
 'oracle data integrator (odi)',
 'oral communication',
 'outlook',
 'panorama',
 'payroll administration',
 'personal data',
 'photoshop',
 'php',
 'pl/sql',
 'power bi',
 'power point',
 'powerpivot',
 'powerquery',
 'priority management',
 'product control',
 'product service',
 'project+',
 'pyspark',
 'python',
 'python (software)',
 'pytorch',
 'qlik',
 'quantitative data',
 'query languages',
 'quotations',
 'r',
 'rapidminer',
 'recovery plans',
 'redshift',
 'requirements engineering',
 'rstudio',
 'rust',
 's3',
 'salesforce',
 'salesforce sales cloud',
 'sap',
 'sap bw',
 'sap erp',
 'sap srm',
 'sas',
 'scala',
 'segment',
 'sharepoint',
 'shell',
 'shiny',
 'sisense',
 'snowflake',
 'social',
 'spark',
 'spotfire',
 'spreadsheet',
 'spring cloud',
 'spss',
 'spss clementine',
 'sql',
 'ssis',
 'ssrs',
 'statistical analysis',
 'statistics',
 'statutory accounting principles (sap)',
 'tableau',
 'talend',
 'targit',
 'technical solution design',
 'tensorflow',
 'timeseries',
 'umachine learning',
 'unix',
 'vba',
 'vbscript',
 'web concepts',
 'yellowfin bi',
 'автоматизация тестирования',
 'администрирование salesforce',
 'анализ бизнес-данных',
 'анализ данных',
 'анализ требований',
 'аналитика',
 'аналитические навыки',
 'английский язык',
 'базы данных',
 'бизнес-аналитика',
 'бизнес-объекты',
 'бизнес-приложения',
 'бизнес-процессы',
 'бизнес-требования',
 'большие массивы данных',
 'бухгалтерский учёт',
 'веб-сервисы',
 'веб-технологии',
 'ведение переговоров',
 'визуализация данных',
 'витрины данных',
 'гибкая методология программирования',
 'данные о клиентах',
 'документация',
 'еда и напитки',
 'законодательные отношения',
 'инвестиционно-банковская деятельность',
 'инженерное дело',
 'интеллектуальный анализ данных',
 'интернет-исследование',
 'информационные технологии',
 'истории пользователей',
 'каталог',
 'качество данных',
 'ключевые показатели деятельности',
 'командная работа',
 'коммуникабельность',
 'коммуникация',
 'компьютерная наука',
 'контроль качества',
 'координация',
 'корпоративные финансы',
 'критическое мышление',
 'лабораторные навыки',
 'маркетинговые исследования',
 'математика',
 'международная логистика',
 'межличностное общение',
 'межсетевая защита',
 'модели данных',
 'моделирование данных',
 'моторы',
 'мсфо',
 'наборы данных',
 'навыки презентаций',
 'написание запросов',
 'написание политики',
 'наука о данных',
 'научно-исследовательская деятельность',
 'недвижимость',
 'немецкий язык',
 'нидерландский язык',
 'облачные вычисления',
 'обмен электронными данными',
 'обработка естественного языка',
 'операционная деятельность',
 'организаторские навыки',
 'организация информационных хранилищ',
 'основные данные',
 'основные показатели',
 'отчетность',
 'панель управления',
 'письменное сообщение',
 'план счетов',
 'планирование возможностей',
 'планирование потребности в материалах',
 'планы проекта',
 'помощь исполнительному директору по административным вопросам',
 'помощь по административным вопросам<!-- --></span>',
 'построение карты бизнес-процессов',
 'построение отношений',
 'предоставление данных',
 'презентации',
 'приемочное испытание',
 'прикладная математика',
 'принятие решений',
 'прогнозирование',
 'прогнозное моделирование',
 'проектирование баз данных',
 'проектирование пользовательского интерфейса (ued)',
 'профессиональные навыки работы с компьютером',
 'профилактическое техническое обслуживание',
 'пфи',
 'работа поставщиков',
 'работа с ключевыми клиентами',
 'разработка систем',
 'рассмотрение заявок',
 'решение задач',
 'решение проблем',
 'розничная торговля',
 'розничная торговля через интернет',
 'сбор данных',
 'сбор требований',
 'сводные таблицы',
 'сегментация рынка',
 'сетевая безопасность',
 'скрам',
 'служба поддержки',
 'соглашения об уровне услуг',
 'сотрудничество',
 'сохраненные процедуры',
 'социальные медиа',
 'социальные навыки',
 'спецификация требований',
 'средства бизнес-аналитики',
 'статистическое моделирование',
 'стратегии ценообразования',
 'стратегия',
 'стратегия ведения бизнеса',
 'творческий подход к решению проблем',
 'тестирование на приемлемость для пользователя',
 'техническая поддержка',
 'технологическая подготовка производства',
 'транспортировка по трубопроводу',
 'управление взаимодействием с корпоративными клиентами',
 'управление вознаграждением работников',
 'управление данными',
 'управление логистикой',
 'управление материалами',
 'управление объемом работ',
 'управление операциями',
 'управление отношениями с заинтересованными сторонами',
 'управление предприятием',
 'управление проектами',
 'урегулирование споров',
 'услуги анализа',
 'финансовая математика',
 'финансовые услуги',
 'финансовый анализ',
 'финансы',
 'французский язык',
 'функциональные требования',
 'целевая цена',
 'цифровой маркетинг',
 'экологическая сбалансированность',
 'экономика',
 'языки программирования']

In [52]:
# найдем хард скиллы, которые встречаются 1-3 раза на весь датасет

df_new_explode_bottom = (df_new_explode.groupby(['job_skills']).agg({'number_vacancy':'count'}).sort_values(by='number_vacancy'\
                                                                    ,ascending=True).reset_index())
df_new_explode_bottom1 = df_new_explode_bottom[df_new_explode_bottom['number_vacancy'].isin([1,2,3])]

df_new_explode_bottom1_skills = df_new_explode_bottom1['job_skills']

# удалим хард скиллы, которые встречается 1-3 раза на весь датасет

df_new_explode_top = df_new_explode.query('job_skills not in @df_new_explode_bottom1_skills')

In [53]:
print('Количество хард-скиллов всего - {a}, количество хард-скиллов, которые встречаются 1-3 раза {b} ({c:.2%})'.\
     format(a=df_new_explode['job_skills'].count(),b=df_new_explode_bottom1_skills.count(),c=df_new_explode_bottom1_skills\
            .count()/df_new_explode['job_skills'].count()))

Количество хард-скиллов всего - 3055, количество хард-скиллов, которые встречаются 1-3 раза 277 (9.07%)

In [54]:
df_new_explode_bottom1_skills.tolist()

['языки программирования',
 'recovery plans',
 'redshift',
 'технологическая подготовка производства',
 'salesforce sales cloud',
 'техническая поддержка',
 'sap bw',
 'sap srm',
 'shiny',
 'sisense',
 'тестирование на приемлемость для пользователя',
 'social',
 'spotfire',
 'spring cloud',
 'управление взаимодействием с корпоративными клиентами',
 'творческий подход к решению проблем',
 'стратегия ведения бизнеса',
 'ssrs',
 'statistical analysis',
 'стратегия',
 'statutory accounting principles (sap)',
 'стратегии ценообразования',
 'targit',
 'technical solution design',
 'tensorflow',
 'timeseries',
 'umachine learning',
 'vbscript',
 'web concepts',
 'spss clementine',
 'quotations',
 'quantitative data',
 'python (software)',
 'marketing campaigns',
 'marketing mix modeling',
 'marketing reporting',
 'matillion',
 'metabase',
 'metrics definition',
 'microsoft dynamics nav',
 'управление объемом работ',
 'mixpanel',
 'mobile switching centre server (mss)',
 'moe',
 'mongodb',
 'new product rollout',
 'oracle data integrator (odi)',
 'oral communication',
 'outlook',
 'panorama',
 'payroll administration',
 'personal data',
 'photoshop',
 'php',
 'pl/sql',
 'управление материалами',
 'сегментация рынка',
 'priority management',
 'product control',
 'product service',
 'project+',
 'pyspark',
 'автоматизация тестирования',
 'администрирование salesforce',
 'социальные навыки',
 'бизнес-приложения',
 'операционная деятельность',
 'организация информационных хранилищ',
 'основные данные',
 'служба поддержки',
 'письменное сообщение',
 'план счетов',
 'планирование возможностей',
 'планирование потребности в материалах',
 'планы проекта',
 'помощь исполнительному директору по административным вопросам',
 'помощь по административным вопросам<!-- --></span>',
 'построение карты бизнес-процессов',
 'построение отношений',
 'приемочное испытание',
 'прикладная математика',
 'прогнозирование',
 'проектирование баз данных',
 'проектирование пользовательского интерфейса (ued)',
 'пфи',
 'работа поставщиков',
 'работа с ключевыми клиентами',
 'разработка систем',
 'рассмотрение заявок',
 'скрам',
 'решение проблем',
 'розничная торговля',
 'розничная торговля через интернет',
 'сбор данных',
 'сводные таблицы',
 'обмен электронными данными',
 'looker (software)',
 'облачные вычисления',
 'научно-исследовательская деятельность',
 'бизнес-процессы',
 'большие массивы данных',
 'бухгалтерский учёт',
 'веб-сервисы',
 'веб-технологии',
 'ведение переговоров',
 'витрины данных',
 'гибкая методология программирования',
 'данные о клиентах',
 'еда и напитки',
 'законодательные отношения',
 'инженерное дело',
 'интеллектуальный анализ данных',
 'интернет-исследование',
 'информационные технологии',
 'каталог',
 'сохраненные процедуры',
 'сотрудничество',
 'контроль качества',
 'координация',
 'корпоративные финансы',
 'лабораторные навыки',
 'международная логистика',
 'межсетевая защита',
 'моторы',
 'навыки презентаций',
 'написание запросов',
 'написание политики',
 'соглашения об уровне услуг',
 'недвижимость',
 'learning',
 'управление логистикой',
 'сетевая безопасность',
 'commerce',
 'environmental',
 'cluster analysis',
 'erd',
 'esprit',
 'урегулирование споров',
 'cloudera',
 'clickhouse',
 'c#',
 'factiva',
 'business support',
 'feature extraction',
 'fivetran',
 'french language',
 'futures',
 'business solution',
 'business case development',
 'business administration',
 'budget tracking',
 'enterprise service bus (esb) architecture',
 'bpmn',
 'elt',
 'coordinating skills',
 'lambda',
 'финансовая математика',
 'data manipulation',
 'data interpretation',
 'услуги анализа',
 'data feeds',
 'database queries',
 'финансовые услуги',
 'dash',
 'dataiku dss',
 'datastage',
 'dax',
 'cultural affairs',
 'dcf valuation',
 'cross-team collaboration',
 'dhcp',
 'digital technology',
 'cross-channel marketing',
 'crm',
 'ecmascript',
 'bitbucket',
 'финансы',
 'gmp (надлежащая производственная практика)',
 'hyperion financial management (hfm)',
 'hypothesis testing',
 'basque',
 'analytical modelling',
 'interpreting data',
 'it business analysis',
 'it solutions',
 'itil',
 'amazon web services (aws)',
 'human behavior',
 'amazon quicksight',
 'jenkins',
 'управление операциями',
 'amazon elastic mapreduce (emr)',
 'amachine learning',
 'экологическая сбалансированность',
 'keras',
 'agile software development',
 'adobe target',
 'abstracting',
 'amazon kinesis',
 'hubspot',
 'industrial internet of things (iiot)',
 'data pipelines',
 'attribution',
 'htmachine learning',
 'application services',
 'цифровой маркетинг',
 'apache spark streaming',
 'apache kafka',
 'analytique',
 'apache spark',
 'управление предприятием',
 'управление отношениями с заинтересованными сторонами',
 'hana',
 'bash',
 'целевая цена',
 'финансовый анализ',
 'бизнес-аналитика',
 'нидерландский язык',
 'data engineering',
 'сбор требований',
 'algorithm development',
 'business case preparation',
 'предоставление данных',
 'наборы данных',
 'профилактическое техническое обслуживание',
 'профессиональные навыки работы с компьютером',
 'мсфо',
 'прогнозное моделирование',
 'принятие решений',
 'amplitude',
 'маркетинговые исследования',
 'критическое мышление',
 'ci/cd',
 'business reviews',
 'документация',
 'kubernetes',
 'german language',
 'sap erp',
 'экономика',
 'rstudio',
 'requirements engineering',
 'спецификация требований',
 'rapidminer',
 'github',
 'query languages',
 'shell',
 'gitlab',
 'google data studio',
 'google sheets',
 'powerquery',
 'google workspace',
 'nlp',
 'julia',
 'kafka',
 'linux',
 'управление вознаграждением работников',
 'domo',
 'анализ требований',
 'data-driven decision making',
 'средства бизнес-аналитики',
 'yellowfin bi',
 'confluence',
 's3',
 'data governance',
 'модели данных',
 'обработка естественного языка',
 'google cloud platform (gcp)',
 'функциональные требования',
 'c++',
 'отчетность',
 'sharepoint',
 'microstrategy',
 'microsoft power query',
 'коммуникабельность',
 'unix',
 'docker',
 'css']

In [55]:
# удалим софт-скиллы и то, что не относится к скиллам

df_new_explode_top = df_new_explode_top.query('job_skills not in ["транспортировка по трубопроводу","управление проектами",\
"управление данными","статистика по компании","социальные медиа","решение задач","панель управления","основные показатели",\
"организаторские навыки","презентации","наука о данных","межличностное общение","коммуникация","командная работа",\
"ключевые показатели деятельности","качество данных","истории пользователей","инвестиционно-банковская деятельность",\
"бизнес-требования","бизнес-объекты","аналитические навыки","аналитика","анализ бизнес-данных","анализ данных",\
"attention to detail","business analysis","data analytics"]')

In [56]:
# уберем middle и senior

senior = df_new_explode_top[df_new_explode_top['title'].str.contains('senior')]['number_vacancy']
df_new_explode_top = df_new_explode_top.query('number_vacancy not in @senior')

middle = df_new_explode_top[df_new_explode_top['title'].str.contains('middle')]['number_vacancy']
df_new_explode_top = df_new_explode_top.query('number_vacancy not in @middle')

In [57]:
# проверим, что убрали middle и senior
df_new_explode_top[df_new_explode_top['title'].str.contains('senior') | df_new_explode_top['title'].str.contains('middle')]

Empty DataFrame
Columns: [number_vacancy, title, location, country, employment_type, company_name, employee_qty, company_field, skills, job_description, applicants, job_skills]
Index: []

**Разобьем все вакансии на продуктовых аналитиков, маркетинговых аналитиков, бизнес-аналитиков, финансовых аналитиков и дата сайнтистов**

In [58]:
# создание функции

def name_vacancy (row):
    
    #for i in row['title']
    if 'product' in row['title']:
        return 'product analyst'
    elif 'marketing' in row['title']:
        return 'marketing analyst'
    elif 'business' in row['title']:
        return 'business analyst'
    elif 'financ' in row['title']:
        return 'finance analyst'
    elif 'scientist' in row['title']:
        return 'data scientist'
    elif 'bi ' in row['title']:
        return 'bi analyst'
    else:
        return 'data analyst'
    
# создание нового столбца с разбивкой по типам аналитиков   
    
df_new_explode_top['name_vacancy'] = df_new_explode_top.apply(name_vacancy,axis=1)

In [59]:
# проверка
df_new_explode_top.groupby('name_vacancy')['number_vacancy'].nunique().sort_values(ascending=False)

name_vacancy
data analyst         538
business analyst      75
data scientist        39
product analyst       19
marketing analyst     17
finance analyst       14
bi analyst            11
Name: number_vacancy, dtype: int64

## Перевод полученной таблицы в формат Excel

In [60]:
df_linkedln1 = df_new_explode_top.to_excel('D:\df_linkedln1.xlsx')